# Generated by Django 2.2.1 on 2019-07-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='avatar.png', upload_to='profile')),
                ('cover', models.ImageField(default='cover.png', upload_to='cover')),
                ('status', models.TextField(default='Enjoying Moments..')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dob', models.CharField(default='DD-MM-YYYY', max_length=12)),
                ('fname', models.CharField(default='First Name', max_length=12)),
                ('lname', models.CharField(default='Last Name', max_length=12)),
                ('gender', models.CharField(default='Gender', max_length=12)),
                ('profile_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Signup')),
            ],
        ),
    ]
